server:
  port: 7004
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
#    password: 89187786606Alex
    password: 123456
    url: jdbc:postgresql://localhost:5432/watershop
    username: postgres
